# =============================================
# CONFIGURACION BASE DE DATOS - ORACLE 21c
# =============================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=isabela
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVIDOR
server.port=8080
spring.application.name=gym-system
logging.level.com.gym=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City
spring.jpa.properties.hibernate.default_schema=SYSTEM
spring.jpa.open-in-view=false

# CAMEL RABBITMQ
camel.component.rabbitmq.hostname=localhost
camel.component.rabbitmq.port-number=5672
camel.component.rabbitmq.username=guest
camel.component.rabbitmq.password=guest